{{- $fullName := include "general.fullname" . -}}
{{- $httpPort := "" -}}
{{- range .Values.container.ports }}
{{- if eq "http" .name }}
{{- $httpPort = .servicePort -}}
{{- end }}
{{- end }}
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ .host }}
      {{- end }}
  {{- end }}
    secretName: {{ .Release.Name }}-{{ .Values.ingress.tls.secretName }}-secret
  rules:
    {{- range .Values.ingress.hosts }}
    -
    {{- if .host }}
      host: {{ tpl .host $ | quote }}
    {{- end }}
      http:
        paths:
          {{- range .paths }}
          - backend:
              service:
                name: {{ $fullName }} 
                port: 
                  number: {{ $httpPort }}
            path: {{ .path }}
            pathType: Prefix
          {{- end }}
    {{- end }}
{{- end }}
