{{- $releaseName := .Release.Name -}}
{{- $releaseNamespace := .Release.Namespace }}
{{- if .Values.secret }}
{{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ .name }}-secret
  namespace: {{ $releaseNamespace }}
data:
{{- if .value }}
{{- range $key, $val := .value }}
   {{- if hasSuffix "filepath" $key }}
   {{ $key | replace ".filepath" "" }}: {{ $.Files.Get $val | b64enc | quote }}
   {{ else }}
   {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- if .volume }}
{{- range $key, $val := .volume }}
   {{- if hasSuffix "filepath" $key }}
   {{ $key | replace ".filepath" "" }}: {{ $.Files.Get $val | b64enc | quote }}
   {{ else }}
   {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
